services:
  - type: web
    name: library-management-system
    runtime: docker
    plan: free
    envVars:
      - key: JAVA_OPTS
        value: "-Xms256m -Xmx256m"
    healthCheckPath: /api/books
    autoDeploy: true
